name: rog-sam
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - pillow
  - matplotlib
  - opencv
  - tqdm
  - pip
  - pip:
      - einops
      - mmcv
      - monai
      - pycocotools
      - tensorboardX
      - timm
      - torchsummary
